### ISSUE TITLE
Typos on the TESlax website

### ISSUE THREAD

**Issue by israndy** [tesLAXApp/tesLAX#10]
Hope this finds you well. Just discovered the app on YouTube and bought the CANServer device to connect to my Tesla Model 3. I hope to discover more about the guts of my car with your app, following JWardell closely.

I was reading thru the teslax.app site trying to figure out how to customize my display. Discovered quite a few simple typos that I thought I would point out so they could be fixed:

<img width="721" alt="Screen Shot 2020-10-02 at 1 02 13 PM" src="https://user-images.githubusercontent.com/23196407/94974515-af3bd580-04c3-11eb-835d-f076fbac1043.png">
<img width="708" alt="Screen Shot 2020-10-02 at 1 03 33 PM" src="https://user-images.githubusercontent.com/23196407/94974517-b1059900-04c3-11eb-9bd2-ddd5d95142fe.png">
<img width="710" alt="Screen Shot 2020-10-02 at 1 05 58 PM" src="https://user-images.githubusercontent.com/23196407/94974518-b2cf5c80-04c3-11eb-912d-6e616bd5c9ba.png">
<img width="735" alt="Screen Shot 2020-10-02 at 1 40 39 PM" src="https://user-images.githubusercontent.com/23196407/94974519-b367f300-04c3-11eb-8eb8-5f4ddd640be0.png">
<img width="722" alt="Screen Shot 2020-10-02 at 1 51 49 PM" src="https://user-images.githubusercontent.com/23196407/94974521-b367f300-04c3-11eb-89fa-9af8eef93023.png">
<img width="732" alt="Screen Shot 2020-10-02 at 2 10 44 PM" src="https://user-images.githubusercontent.com/23196407/94974522-b4008980-04c3-11eb-9b95-b92d25d32caa.png">
<img width="728" alt="Screen Shot 2020-10-02 at 2 17 04 PM" src="https://user-images.githubusercontent.com/23196407/94974523-b4992000-04c3-11eb-8c6c-6f8b4b20f9c1.png">
<img width="731" alt="Screen Shot 2020-10-02 at 2 20 35 PM" src="https://user-images.githubusercontent.com/23196407/94974524-b4992000-04c3-11eb-90a8-9628f5e8e0d7.png">

**Comment by jake-b** [comment]
Thanks!  Yes, I should proof read things better, and documentation is often an afterthought.  (These typos likely exist in the help document in the app as well.)   I'll fix them up this weekend.  Thanks!

**Comment by jake-b** [comment]
Typos on website (and in app help file) have been corrected.  Thanks for your attention to detail, as I'm usually more focused on the code then on the documentation. :)
