### ISSUE TITLE
Ipad gauge limet

### ISSUE THREAD

**Issue by LeoZalewski** [tesLAXApp/tesLAX#12]
Great app
On iPhone "+ Add New" seams to be limits less
On Ipad "+ Add New" limits to about 16 gauges, related to where the "+ Add New" is on the screen.

**Comment by jake-b** [comment]
Hi there.  Yeah, I've seen that before, and its a quirk of SwiftUI.  An upcoming update should fix this issue.

**Comment by LeoZalewski** [comment]
Is it possible to rename a gauge description?

**Comment by jake-b** [comment]
In the signal list, you can assign a "display name" to a signal which will change what is shown under the gauge.

Also feel free to join us on discord, to chat amongst other users: https://discord.gg/umZ8wvG

**Comment by jake-b** [comment]
I believe this issue is resolved in recent versions.  If not, please re-open the ticket :)
