### ISSUE TITLE
iPhone 12 Pro plus gauge limit 

### ISSUE THREAD

**Issue by maltalkstesla** [tesLAXApp/tesLAX#13]
Hi I am a youtube blogger and I am featuring your product in a series I’m doing on my channel Mal Talks Tesla 
But have noticed when I use my iPhone 10x max the gauges are fully displayed On my iPhone 12 plus pro max it doesn't display fully can this be fixed also can you give me a list of the abbreviation  terms used  such as socu 1292
BMS these will be helpful when explaining last but not least one you set a new page how a you editors name as I don't see how this is done 
Regards
Mal

**Comment by jake-b** [comment]
Hi can you send me a screenshot of the behavior you are seeing?

The signal and message names are inscrutable.  They are reverse engineered by the Tesla community as they are not provided by Tesla.  "SOC" for example, means "State of Charge".  BMS means "Battery Management System".  I don't know of anyone maintaining a full list of definitions. (And I'm not sure if we even know what they all mean)

Also, if you like you can join us for discussion on Discord at https://discord.gg/D6nKsCxegr - there is a small community where I and others can help answer your questions.

**Comment by maltalkstesla** [comment]
Here is the picture [cid:B3C60ED9-3B32-42DC-B81A-BD1249EA9A44-L0-001]


[cid:17144051-AC61-440E-BA12-EEC4E062B0F0-L0-001]
As you see iPhone 12 pro max. Limits the view
Regards
Mal
If you can’t  Malcan

On 23 Dec 2020, at 15:32, jake-b <notifications@github.com> wrote:

﻿

Hi can you send me a screenshot of the behavior you are seeing?

The signal and message names are inscrutable. They are reverse engineered by the Tesla community as they are not provided by Tesla. "SOC" for example, means "State of Charge". BMS means "Battery Management System". I don't know of anyone maintaining a full list of definitions. (And I'm not sure if we even know what they all mean)

Also, if you like you can join us for discussion on Discord at https://discord.gg/D6nKsCxegr - there is a small community where I and others can help answer your questions.

**Comment by maltalkstesla** [comment]
Here is the view from I phoned X pro max

[cid:010A2750-2795-4242-833D-270A29D04A38]

[cid:9078BE2A-3689-48CD-B916-416B3F6E2C29-L0-001]
If you can’t  Malcan

On 23 Dec 2020, at 15:56, Mal Wayne <mal@malcan.co.uk> wrote:

﻿ Here is the picture
<image0.jpeg>



<image1.jpeg>

As you see iPhone 12 pro max. Limits the view
Regards
Mal
If you can’t  Malcan

On 23 Dec 2020, at 15:32, jake-b <notifications@github.com> wrote:

﻿

Hi can you send me a screenshot of the behavior you are seeing?

The signal and message names are inscrutable. They are reverse engineered by the Tesla community as they are not provided by Tesla. "SOC" for example, means "State of Charge". BMS means "Battery Management System". I don't know of anyone maintaining a full list of definitions. (And I'm not sure if we even know what they all mean)

Also, if you like you can join us for discussion on Discord at https://discord.gg/D6nKsCxegr - there is a small community where I and others can help answer your questions.

**Comment by jake-b** [comment]
Looks like the GitHub email system ate the attachments.  Can you try posting through the website?

**Comment by maltalkstesla** [comment]
![E9C6FE01-7544-4126-A069-B82BEC3F1FA7](https://user-images.githubusercontent.com/76474322/103024925-ae599380-4548-11eb-998b-038c0ff19b70.jpeg)
![6DDE8D3C-684B-47F5-B90F-6E3A07FEE656](https://user-images.githubusercontent.com/76474322/103024934-b285b100-4548-11eb-9d77-8805343f8152.jpeg)
![9828BF12-6E79-40A9-B954-E17A79BDFF55](https://user-images.githubusercontent.com/76474322/103024936-b3b6de00-4548-11eb-8ca4-23c9341387a0.jpeg)
![EE523BA4-66B9-49C4-8935-2C4CA307F419](https://user-images.githubusercontent.com/76474322/103024937-b44f7480-4548-11eb-9894-fe8cde32c11c.jpeg)
![BDCDD45F-3C8B-49D4-948C-3AB2C9A88611](https://user-images.githubusercontent.com/76474322/103024940-b4e80b00-4548-11eb-92f3-31d8b280afdd.jpeg)
![D38ED6F5-2D24-4073-A8C7-591F57129D85](https://user-images.githubusercontent.com/76474322/103024945-b580a180-4548-11eb-868c-ca8666c7385e.jpeg)
![457EB02D-842A-43ED-886E-B833EFB7DCDE](https://user-images.githubusercontent.com/76474322/103024949-b6193800-4548-11eb-9202-98e14649cb2f.jpeg)
![ADECD439-6E2D-4945-A8AD-ED1D4AAB0E21](https://user-images.githubusercontent.com/76474322/103024952-b74a6500-4548-11eb-913e-e8f0d6ea9bd4.jpeg)

**Comment by maltalkstesla** [comment]
Hopefully you got it. excuse other pictures there what I'm working on my YouTube channel 
Mal Talks Tesla,I'm using Teslax  to show what happens when the screen goes out

**Comment by jake-b** [comment]
OK, so if I understand correctly, I think you can make the layout a bit better.

Press the "(...)" button in the upper right, you can configure the size of the gauges (with the slider) and the number of columns.

Text truncation (when text get cutoff with "..." is controlled by the operating system's layout engine, so I don't have much control over that, unfortunately.  Worst case, you can edit the signals in the "Signal List" to provide a shorter, more descriptive 'Display Name' which will be used for the gagues.
