### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by fotiDim** [tesLAXApp/tesLAX#17]
Hi, I am a fellow iOS developer and Tesla owner. I made a video on Youtube featuring tesLAX and the Panda OBD dongle. I wanted to send it to @jake-b but couldn’t find any contact info. I can post it here if you don’t mind the shameless plug. In any case thank you for this great app!

**Comment by jake-b** [comment]
Hi. Sure. Here or come find me and some other interesting people on discord. https://discord.gg/9SwTNMBc


Thanks for your interest!
