### ISSUE TITLE
iOS 12 support

### ISSUE THREAD

**Issue by ShadyNawara** [tesLAXApp/tesLAX#21]
Hi,
I have an older iPad mini 2 that only supports up to iOS 12.5.5 that I would love to just leave in the car running this app.
If there isn't any strong dependencies on iOS 13 would you consider lowering the minimum version required.

**Comment by jake-b** [comment]
Sadly the app is largely built on SwiftUI.  It was an excuse to learn SwuftUI in fact, but now I have to live with the limitations and quirks if SwiftUI…. And this is one such limitation.

**Comment by ShadyNawara** [comment]
good to know, thank you so much answering.
