### ISSUE TITLE
Custom Ranges

### ISSUE THREAD

**Issue by JoshuaHolme** [tesLAXApp/tesLAX#29]
It'd be great to define custom ranges for the gauges. For instance BMS_nominalEnergyRemaining has a static scale of 0 to 204.6kWh. I don't have a battery that big, so it'd be nice to set it manually to a lower amount.

**Comment by jake-b** [comment]
This is already possible.

1. In the _Signal List_, make sure the signal you're monitoring has the Max/Min values you wish to track with static max/min.
2. In the view configuration ("..." upper night, "_Edit Gagues/Layout_") find the row for the gauge you want to have a static range.  Then edit the entry.  Change "Lifetime Max/Min" to "Static")

That should do it.  Let me know if you have any trouble.

**Comment by jake-b** [comment]
I haven't heard back so I assume you've got things working. I. will close this ticket for now.
