### ISSUE TITLE
Single Wire CAN

### ISSUE THREAD

**Issue by bluntd42** [tesLAXApp/tesLAX#31]
Hello. I am interested in using tesLAX with a Bluetooth link to an OBDLink MX+ device in a General Motors vehicle to monitor the Single Wire CAN bus. I have developed my own DBC file and imported it into tesLAX. However, tesLAX seems to be hard coded to use an 11-bit 500kbps protocol (from memory, protocol 33) with the OBDLink MX+ and I need a 29-bit 33.3kbps protocol (protocol 62) connection. Is this at all possible? Could a feature be added to tesLAX to allow different MX+ connection protocols?

**Comment by jake-b** [comment]
Hi! Sorry for the delayed response.

Sorry to report, right now the app does not do 29-bit addresses.  It would take some work to make that possible, and I don't have a 29-bit car to develop against.

Thanks for the interest.  It's not out of the question that this feature will appear in the future, but I don't have any specific roadmap for it currently.
