### ISSUE TITLE
UI enhancement: Smaller gauge layout

### ISSUE THREAD

**Issue by dburkland** [tesLAXApp/tesLAX#8]
I have been a long time user of Scan My Tesla however prefer iOS and thus trying to migrate my custom Scan My Tesla dashboards over to tesLAX. With that said would it be possible to add the ability to select a smaller gauge size so you could fit a few more rows of gauges on a given screen? I posted a reference shot of one of my Scan my Tesla dashboards along with one I am currently building out in tesLAX. 

[Scan My Tesla Dashboard](https://www.dropbox.com/s/5rhqjvan9mqm6q9/IMG_1280.jpeg?dl=0)
[tesLAX Dashbaord](https://www.dropbox.com/s/rvmfsp212pq80i5/IMG_0071.jpeg?dl=0)

Thanks,

Dan

**Comment by jake-b** [comment]
Hi Dan,

Are you interested in joining the beta?  If so, just find a way to privately send me your email address and I'll add you to the TestFlight for the next beta.  I think you'll like some of the upcoming features, which address your feature request.

**Comment by dburkland** [comment]
Absolutely! Are you on twitter? I can shoot you my address in a DM if that works.

Thanks,

Dan

**Comment by jake-b** [comment]
That works. @AllAboutJake

**Comment by jake-b** [comment]
I believe this issue has been resolved in recent versions.  Please re-open if you still have issues. :)
